# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services.protos.rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStory = channel.unary_unary(
                '/rag.RagService/GetStory',
                request_serializer=rag__pb2.StoryRequest.SerializeToString,
                response_deserializer=rag__pb2.StoryResponse.FromString,
                _registered_method=True)
        self.GetSurpriseBox = channel.unary_unary(
                '/rag.RagService/GetSurpriseBox',
                request_serializer=rag__pb2.SurpriseBoxRequest.SerializeToString,
                response_deserializer=rag__pb2.SurpriseBoxResponse.FromString,
                _registered_method=True)
        self.GetActiveInteractionMemory = channel.unary_unary(
                '/rag.RagService/GetActiveInteractionMemory',
                request_serializer=rag__pb2.MemoryRequest.SerializeToString,
                response_deserializer=rag__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.GetICanMemory = channel.unary_unary(
                '/rag.RagService/GetICanMemory',
                request_serializer=rag__pb2.MemoryRequest.SerializeToString,
                response_deserializer=rag__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.GetAgentAllMemory = channel.unary_unary(
                '/rag.RagService/GetAgentAllMemory',
                request_serializer=rag__pb2.MemoryRequest.SerializeToString,
                response_deserializer=rag__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.GetChildAllMemory = channel.unary_unary(
                '/rag.RagService/GetChildAllMemory',
                request_serializer=rag__pb2.MemoryRequest.SerializeToString,
                response_deserializer=rag__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.GetRelateMemory = channel.unary_unary(
                '/rag.RagService/GetRelateMemory',
                request_serializer=rag__pb2.MemoryRequest.SerializeToString,
                response_deserializer=rag__pb2.MemoryResponse.FromString,
                _registered_method=True)
        self.RetrieveSong = channel.unary_unary(
                '/rag.RagService/RetrieveSong',
                request_serializer=rag__pb2.RetrieveSongRequest.SerializeToString,
                response_deserializer=rag__pb2.RetrieveSongResponse.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSurpriseBox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveInteractionMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetICanMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentAllMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildAllMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelateMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStory,
                    request_deserializer=rag__pb2.StoryRequest.FromString,
                    response_serializer=rag__pb2.StoryResponse.SerializeToString,
            ),
            'GetSurpriseBox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSurpriseBox,
                    request_deserializer=rag__pb2.SurpriseBoxRequest.FromString,
                    response_serializer=rag__pb2.SurpriseBoxResponse.SerializeToString,
            ),
            'GetActiveInteractionMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveInteractionMemory,
                    request_deserializer=rag__pb2.MemoryRequest.FromString,
                    response_serializer=rag__pb2.MemoryResponse.SerializeToString,
            ),
            'GetICanMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetICanMemory,
                    request_deserializer=rag__pb2.MemoryRequest.FromString,
                    response_serializer=rag__pb2.MemoryResponse.SerializeToString,
            ),
            'GetAgentAllMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentAllMemory,
                    request_deserializer=rag__pb2.MemoryRequest.FromString,
                    response_serializer=rag__pb2.MemoryResponse.SerializeToString,
            ),
            'GetChildAllMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildAllMemory,
                    request_deserializer=rag__pb2.MemoryRequest.FromString,
                    response_serializer=rag__pb2.MemoryResponse.SerializeToString,
            ),
            'GetRelateMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelateMemory,
                    request_deserializer=rag__pb2.MemoryRequest.FromString,
                    response_serializer=rag__pb2.MemoryResponse.SerializeToString,
            ),
            'RetrieveSong': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveSong,
                    request_deserializer=rag__pb2.RetrieveSongRequest.FromString,
                    response_serializer=rag__pb2.RetrieveSongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetStory',
            rag__pb2.StoryRequest.SerializeToString,
            rag__pb2.StoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSurpriseBox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetSurpriseBox',
            rag__pb2.SurpriseBoxRequest.SerializeToString,
            rag__pb2.SurpriseBoxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveInteractionMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetActiveInteractionMemory',
            rag__pb2.MemoryRequest.SerializeToString,
            rag__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetICanMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetICanMemory',
            rag__pb2.MemoryRequest.SerializeToString,
            rag__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentAllMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetAgentAllMemory',
            rag__pb2.MemoryRequest.SerializeToString,
            rag__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildAllMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetChildAllMemory',
            rag__pb2.MemoryRequest.SerializeToString,
            rag__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelateMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetRelateMemory',
            rag__pb2.MemoryRequest.SerializeToString,
            rag__pb2.MemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/RetrieveSong',
            rag__pb2.RetrieveSongRequest.SerializeToString,
            rag__pb2.RetrieveSongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
